<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bvccon" nsURI="bvccon" nsPrefix="bvccon">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="NFRModel">
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nfrs" lowerBound="1" upperBound="-1"
        eType="#//NFRSoftgoal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" lowerBound="1"
        upperBound="-1" eType="#//NFRSoftgoalContribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributionsOperationals"
        lowerBound="1" upperBound="-1" eType="#//NFRSoftgoalContributionOperational"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nfroperationalizations"
        lowerBound="1" upperBound="-1" eType="#//NFROperationalization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NFRElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NFRLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="NFRSoftgoal" eSuperTypes="#//NFRElement">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="internal"/>
      <details key="label.icon" value="false"/>
      <details key="label" value="name"/>
      <details key="size" value="100,30"/>
      <details key="border.color" value="0,0,0"/>
      <details key="border.style" value="dash"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NFRSoftgoalPriority" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NFROperationalization" eSuperTypes="#//NFRElement">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="label.placement" value="internal"/>
      <details key="label.icon" value="false"/>
      <details key="label" value="name"/>
      <details key="size" value="100,30"/>
      <details key="border.color" value="0,0,0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NFRSoftgoalContribution" eSuperTypes="#//NFRLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//NFRSoftgoal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//NFRSoftgoal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NFRSoftgoalContributionOperational"
      eSuperTypes="#//NFRLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//NFROperationalization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//NFRSoftgoal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BreakContribution" eSuperTypes="#//NFRSoftgoalContributionOperational">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="--"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MakeContribution" eSuperTypes="#//NFRSoftgoalContributionOperational">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="++"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrContribution" eSuperTypes="#//NFRSoftgoalContribution">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="OR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndContribution" eSuperTypes="#//NFRSoftgoalContribution">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="AND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EqualContribution" eSuperTypes="#//NFRSoftgoalContributionOperational">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HurtContribution" eSuperTypes="#//NFRSoftgoalContributionOperational">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HelpContribution" eSuperTypes="#//NFRSoftgoalContributionOperational">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="+"/>
  </eClassifiers>
</ecore:EPackage>
